@WebAPI_HostAddress = http://localhost:5099
POST {{WebAPI_HostAddress}}/api/meal/addMeal
Accept: application/json
Content-Type: application/json
{
    "Name": "Energy Boost Snack",
    "Type": "Mic-Dejun",
    "Description": "A high-energy snack with peanut butter and banana slices.",
    "FoodNames": ["Peanut Butter", "Banana"]
}

###
