@WebAPI_HostAddress = http://localhost:5099
POST {{WebAPI_HostAddress}}/api/meal/addLikeToMeal
Accept: application/json
Content-Type: application/json
{    "NameOfMeal": "Light Dinner",
     "NameOfUser": "Mihneas22"
}
###
